apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipego-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipego-ai
  template:
    metadata:
      labels:
        app: recipego-ai
    spec:
      containers:
        - name: recipego-ai
          image: recipego-ai:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
          envFrom:
            - configMapRef:
                name: app-config
