# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: recipego-ai-service
spec:
  type: NodePort  # 로컬 접근을 위해 NodePort 사용
  selector:
    app: recipego-ai
  ports:
    - port: 80
      targetPort: 8001
      nodePort: 30080  # http://localhost:30080 에서 접근 가능
