# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort  # 로컬 접근을 위해 NodePort 사용
  selector:
    app: fastapi-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080  # http://localhost:30080 에서 접근 가능
