# emojiMap_full_ko.js를 기반으로 한 한글 매핑
EMOJI_MAP = {
    "kelp": "다시마",
    "mung_bean_sprouts": "숙주나물",
    "salmon": "연어",
    "lamb": "양고기",
    "teriyaki_sauce": "데리야끼 소스",
    "white_rice": "백미",
    "paprika": "파프리카",
    "abalone": "전복",
    "salad": "샐러드",
    "Makgeolli": "막걸리",
    "dried_pollack_strips": "황태채",
    "mixed_grain_rice": "잡곡",
    "green_onion": "대파",
    "dried_anchovy": "마른 멸치",
    "red_pepper_powder": "고춧가루",
    "pork_back_ribs": "돼지 등갈비",
    "Strawberry_milk": "딸기우유",
    "Rice_noodles": "쌀국수",
    "butter": "버터",
    "Ice_cream": "아이스크림",
    "kimbap": "김밥",
    "sausage": "소시지",
    "chipotle_sauce": "치폴레 소스",
    "red_chili_paste": "고추장",
    "shrimp": "새우",
    "Perilla_leaves": "깻잎",
    "minced_garlic": "다진 마늘",
    "Soju": "소주",
    "sugar": "설탕",
    "sea_squirt": "멍게",
    "Oyster_mushrooms": "느타리버섯",
    "sesame_oil": "참기름",
    "zucchini": "애호박",
    "beef": "소고기",
    "cucumber": "오이",
    "shiitake_mushroom": "표고버섯",
    "Juice": "주스",
    "balsamic_vinegar": "발사믹 식초",
    "mussel": "홍합",
    "pork_belly": "삼겹살",
    "pork_neck": "목살",
    "broccoli": "브로콜리",
    "dumpling": "만두",
    "brown_rice": "현미",
    "grape": "포도",
    "Mozzarella_cheese": "모짜렐라 치즈",
    "honey": "꿀",
    "mayonnaise": "마요네즈",
    "scallop": "가리비",
    "pepper": "후추",
    "Chocolate_milk": "초코우유",
    "fish": "어육",
    "lettuce": "상추",
    "basil": "바질",
    "meatball": "미트볼",
    "dried_shrimp": "건새우",
    "whole_grain_mustard": "홀그레인 머스타드",
    "curry_powder": "카레 가루",
    "tomato_sauce": "토마토 소스",
    "Beer": "맥주",
    "saffron": "사프란",
    "tomato": "토마토",
    "chili_sauce": "칠리소스",
    "duck": "오리",
    "avocado": "아보카도",
    "sweet_potato": "고구마",
    "Tea": "차",
    "pineapple": "파인애플",
    "macaroni": "마카로니",
    "fish_sauce": "피시소스",
    "flying_fish_roe": "날치알",
    "yogurt": "요거트",
    "minced_ginger": "다진 생강",
    "salt": "소금",
    "sea_urchin_roe": "성게알",
    "whipping_cream": "휘핑크림",
    "Canned_corn": "옥수수 통조림",
    "milk": "우유",
    "Canned_beans": "콩 통조림",
    "Sliced_cheese": "슬라이스 치즈",
    "ginger": "생강",
    "fermented_soybean_paste": "청국장",
    "watermelon": "수박",
    "cherry": "체리",
    "salmon_roe": "연어알",
    "seasoned_dried_squid": "진미채",
    "banana": "바나나",
    "ribs": "갈비",
    "peach": "복숭아",
    "sirloin": "등심",
    "bok_choy": "청경채",
    "Wine": "와인",
    "Yogurt_drink": "요구르트 음료",
    "button_mushroom": "양송이 버섯",
    "flavored_soy_sauce": "맛간장",
    "sliced_rice_cake": "떡국 떡",
    "bacon": "베이컨",
    "soy_sauce": "간장",
    "buldak_sauce": "불닭소스",
    "seaweed": "미역",
    "chili_pepper": "고추",
    "matsutake_mushroom": "송이버섯",
    "chili_flakes": "칠리 플레이크",
    "kimchi": "김치",
    "oyster_sauce": "굴소스",
    "spam": "스팸",
    "Canned_salmon": "연어 통조림",
    "clam": "바지락",
    "blueberry": "블루베리",
    "perilla_oil": "들기름",
    "napa_cabbage": "배추",
    "cabbage": "양배추",
    "apple": "사과",
    "Coffee": "커피",
    "crab": "게",
    "radish": "무",
    "octopus": "문어",
    "jujube": "대추",
    "vinegar": "식초",
    "lemon": "레몬",
    "bean_sprout": "콩나물",
    "red_onion": "적색 양파",
    "onion": "양파",
    "Bag_ramen": "봉지 라면",
    "chicken_drumstick": "닭 다리살",
    "garlic": "마늘",
    "condensed_milk": "연유",
    "Water": "물",
    "oregano": "오레가노",
    "sprite": "사이다",
    "cream_cheese": "크림치즈",
    "Somyeon": "소면",
    "Parmesan_cheese": "파마산 치즈",
    "strawberry": "딸기",
    "olive_oil": "올리브 오일",
    "spinach": "시금치",
    "margarine": "마가린",
    "pork_hind_leg": "돼지 뒷다리살",
    "pear": "배",
    "cumin": "커민",
    "cup_ramen": "컵라면",
    "squid": "오징어",
    "water_parsley": "미나리",
    "pollock_roe": "대구 알",
    "chive": "부추",
    "orange": "오렌지",
    "mango": "망고",
    "Canned_tuna": "참치캔",
    "Canned_tomatoes": "토마토 통조림",
    "Sparkling_water": "탄산수",
    "Doubanjang": "두반장",
    "ham": "햄",
    "laver": "김",
    "celery": "샐러리",
    "mala_sauce": "마라 소스",
    "carrot": "당근",
    "maple_syrup": "메이플 시럽",
    "potato": "감자",
    "mustard": "머스타드",
    "kiwi": "키위",
    "instant_rice": "즉석밥",
    "plum": "자두",
    "soybean_paste": "된장",
    "lasagna_sheet": "라자냐 시트",
    "hoisin_sauce": "해선장",
    "cod_roe": "명란",
    "egg": "계란",
    "lobster": "랍스터",
    "Canned_whelk": "골뱅이 통조림",
    "cauliflower": "콜리플라워",
    "Instant_curry": "즉석카레",
    "instant_soup": "즉석국",
    "penne": "펜네",
    "rosemary": "로즈마리",
    "Canned_pizza_sauce": "피자 소스",
    "Canned_fruits": "과일 통조림",
    "cooking_syrup": "요리당",
    "ginseng": "인삼",
    "chicken_breast": "닭 가슴살",
    "fresh_cream": "생크림",
    "tuna": "참치",
    "king_oyster_mushroom": "새송이버섯",
    "Canned_seafood": "해물 통조림",
    "Ramen_noodles": "라멘사리",
    "Udon_noodles": "우동사리",
    "chicken_wing": "닭날개",
    "Canned_mackerel": "고등어 통조림",
    "alfredo_sauce": "알프레도 소스",
    "spaghetti": "스파게티면",
    "chicken_thigh": "닭 허벅지살",
    "enoki_mushroom": "팽이버섯",
    "flounder": "광어",
    "Ciabatta": "치아바타",
    "Naengmyeon_noodles": "냉면사리",
    "pork_front_leg": "돼지 앞다리살",
    "for_bulgogi": "불고기용",
    "Jjolmyeon": "쫄면",
    "Canned_clams": "조개 통조림",
    "Canned_vegetables": "채소 통조림",
    "eggplant": "가지",
    "shank": "우둔살",
    "plain_bread": "식빵",
    "Ramyeon_noodles": "라면사리",
    "Chinese-style_noodles": "중화면",
    "fusilli": "푸실리",
    "cilantro": "고수",
    "thyme": "타임",
    "BBQ_sauce": "BBQ 소스",
    "Kalguksu_noodles": "칼국수면",
    "cooking_oil": "식용유",
    "Glass_noodles": "당면",
    "brisket": "차돌박이",
    "Baguette": "바게트",
    "Canned_soup": "스프 통조림",
    "Croissant": "크로와상",
    "Canned_potatoes": "감자 통조림",
    "Cheddar_cheese": "체다 치즈",
    "nuts": "견과류"
}


def get_korean_name(english_label):
    """영어 라벨을 한글 이름으로 변환"""
    return EMOJI_MAP.get(english_label, english_label)


def get_english_label(korean_label):
    """한글 라벨을 영어 라벨로 역변환"""
    # EMOJI_MAP의 키-값을 뒤집어서 한글→영어 매핑 생성
    reverse_map = {v: k for k, v in EMOJI_MAP.items()}
    return reverse_map.get(korean_label, korean_label) 